# Docker composeのバージョン
version: "3.9"
# コンテナを定義
services:
  db: # コンテナの名前(任意?)
    # DockerHubにあるmySQLの5.7バージョンのイメージ
    image: mysql:5.7 
    volumes:  # volumesで定義したdb_dataを/var/lib/mysqlにmountしている
              ## mount ・・・ volumesで定義したフォルダを同期させているイメージ 
      - db_data:/var/lib/mysql
    restart: always
    # 環境変数を設定
    environment:
      # スーパーユーザーのrootアカウントのパスワードを指定
      MYSQL_ROOT_PASSWORD: somewordpress
      # イメージ起動時に作成するデータベース名を指定
      MYSQL_DATABASE: wordpress
      # 新規ユーザーのユーザー名とパスワード
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress: # コンテナの名前(任意?)
    depends_on:
      - db
    # DockerHubにあるwordpressの最新バージョンのイメージ
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  # 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wordpress_docker_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db
    ports:
      - 8890:80
# dockerボリュームを設定
## 設定しないとdockerをシャットダウンしたときデータベースが消えてしまう
volumes:
  db_data: {}
  wordpress_data: {}